version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - mkdir packages/frontend/dist
      - pnpm frontend-build
      - aws s3 sync packages/frontend/dist s3://kldesign.zuguangtong.xyz
  post_build:
    commands:
      - echo Deployment completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: packages/frontend/dist

cache:
  paths:
    - node_modules
    - packages/frontend/node_modules